services:
  lywsd03mmc-passive:
    image: sydneymrcat/mitemperature:latest
    container_name: mitemperature
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    cap_add:
      - NET_RAW
      - NET_ADMIN
    security_opt:
      - seccomp=unconfined
